defaults:
    - override hydra/hydra_logging: none
    - override hydra/job_logging: none

parameter:
    dataset_path: ./dataset
    checkpoint_path: ./checkpoint/training_${now:%Y%m%d%H%M%S}
    device: gpu
    batch_size: 32
    num_workers: 16
    learning_rate: 0.0001
    num_iterations: 500000
    report_interval: 100
    save_interval: 10000

hydra:
    run:
        dir: ${parameter.checkpoint_path}
    sweep:
        dir: ${parameter.checkpoint_path}
